<!-- Aqui code nico -->
<div id="wrap">
    <!--<h1>Send a message</h1>-->
    <div id='form_wrap'>
        <form>
            <p>Hello friend,</p>
            <label for="email">Your Message : </label>
            <textarea  name="message" value="Your Message" id="message" ></textarea>
            <p>Info,</p>	
            <label for="name">Name: </label>
            <input type="text" name="name" value="" id="name" />
            <label for="email">Email: </label>
            <input type="text" name="email" value="" id="email" />
            <input type="submit" name ="submit" value="Now, I send, thanks!" />
        </form>
    </div>
</div>