<div id="Fader" class="fader">
    <div id="pager"></div>
    <!--                    <div id="pause">&asymp;</div>
                        <div id="play">&Delta;</div>
                        <div id="next">&rang;</div>
                        <div id="prev">&lang;</div>-->
    <div id="Slider">

        <div class="items">
            <img src="<?php echo BASE_URL_IMG; ?>design/banner_1.jpg">
            <!--                            <div class="info">
                                            <h2>The Secret Gathering</h2>
                                            <p>This is the moment, captured in time. <a href="">Learn more</a></p>
                                        </div>-->
        </div>
        <div class="items">
            <img src="<?php echo BASE_URL_IMG; ?>design/banner_2.jpg">
            <!--                            <div class="info">
                                            <h2>The Secret Gathering</h2>
                                            <p>This is the moment, captured in time. <a href="">Learn more</a></p>
                                        </div>-->
        </div>
        <div class="items">
            <img src="<?php echo BASE_URL_IMG; ?>design/banner_3.jpg">
            <!--                            <div class="info">
                                            <h2>The Secret Gathering</h2>
                                            <p>This is the moment, captured in time. <a href="">Learn more</a></p>
                                        </div>-->
        </div>
        <div class="items">
            <img src="<?php echo BASE_URL_IMG; ?>design/banner_4.jpg">
            <!--                            <div class="info">
                                            <h2>The Secret Gathering</h2>
                                            <p>This is the moment, captured in time. <a href="">Learn more</a></p>
                                        </div>-->
        </div>
    </div>
</div>
