<div class="footer_widget">
    <div class="widget">
        <h3>Do you have any question?</h3>
        <ul id="widget_recent_post">
<!-- BEGIN ProvideSupport.com Graphics Chat Button Code -->
<div id="ci2KCT" style="z-index:100;position:absolute"></div><div id="sc2KCT" style="display:inline"></div><div id="sd2KCT" style="display:none"></div><script type="text/javascript">var se2KCT=document.createElement("script");se2KCT.type="text/javascript";var se2KCTs=(location.protocol.indexOf("https")==0?"https":"http")+"://image.providesupport.com/js/13ysac9no0s401omwaoa6iobw9/safe-standard.js?ps_h=2KCT&ps_t="+new Date().getTime();setTimeout("se2KCT.src=se2KCTs;document.getElementById('sd2KCT').appendChild(se2KCT)",1)</script><noscript><div style="display:inline"><a href="http://www.providesupport.com?messenger=13ysac9no0s401omwaoa6iobw9">Online Chat</a></div></noscript>
<!-- END ProvideSupport.com Graphics Chat Button Code -->
        <div id="wrapperPage">
        </ul> 
    </div>

</div>