<div class="footer_widget">
    <div class="widget">
        <h3>Custom Backing Tracks</h3>	
        <div class="textwidget">
            We do realize custom backing tracks from scratch. If you can’t find the song you’re looking for we can make it for you! We are backing tracks programmers. Request a quote now <a href="mailto:superbackingtracks@gmail.com?subject=Quote request">click here.</a>                                
            <noscript>&lt;p&gt;&lt;img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100545017ns.gif" /&gt;</noscript></div>
    </div>
</div>