<div class="widget">
    <h3>How to buy</h3>
    <div class="buy-step">
        <span class=" push">1</span> 
        Search for your songs using the searcher. 
    </div>
    <div class="buy-step">
        <span class=" push">2</span> 
        Select the Version <i data-toggle="modal" data-target="#myModal" class="fa fa-question-circle"></i> Click add to cart to add the songs to the cart.
    </div>
    <div class="buy-step">
        <span class=" push">3</span> 
        Go to the cart at the top of the website.
    </div>
    <div class="buy-step">
        <span class=" push">4</span> 
        Proceed to secure checkout trough Paypal.
    </div>
</div>