<div class="widget">
    <h3>Sort Beats by Genre Widget</h3>
    <ul>
        <li class="genre">
            <ul>
                <li class="cat-item cat-item-20"><a href="https://demo.musicmakertheme.com/genre/club/">Club</a> (4)
                </li>
                <li class="cat-item cat-item-16"><a href="https://demo.musicmakertheme.com/genre/hip-hop/">Hip Hop</a> (7)
                </li>
                <li class="cat-item cat-item-18"><a href="https://demo.musicmakertheme.com/genre/rb/">R&amp;B</a> (1)
                </li>
                <li class="cat-item cat-item-36"><a href="https://demo.musicmakertheme.com/genre/street/">Street</a> (5)
                </li>
                <li class="cat-item cat-item-19"><a href="https://demo.musicmakertheme.com/genre/streets/">Streets</a> (5)
                </li>
                <li class="cat-item cat-item-21"><a href="https://demo.musicmakertheme.com/genre/west-coast/">West Coast</a> (6)
                </li>
            </ul>
        </li>
    </ul> 
</div>