<div id="search">
    <form method="get" id="search" action="javascript:void(0)"> 
        <input autocomplete="off" type="text" class="header_site_search mobile_hide form-controller" placeholder="Search your song" name="s" id="s">
        <div id="results_search"></div>

        <button class="btn btn-info" type="button"><img style="width: 20px;position: relative;vertical-align: bottom;" src="<?= BASE_URL_IMG ?>165.gif" alt="Search" title="Search"></button>
    </form>
</div>