
<div class="navigation_holder nav_top_line " style="background: rgb(27, 29, 29)">
    <div class="navigation_inside_container">
        <div id="navigation" role="navigation" class="mobile_hide">
            <div class="header-menu">
                <ul id="menu-navigation" class="menu">
                    <li><a href="<?= BASE_URL; ?>">Home</a>
                    </li>
                    <li><a href="<?= BASE_URL; ?>full-song-list/">Full song list</a></li>

                    <li><a href="<?= BASE_URL; ?>from-a-to-z/">From a to z</a>
                        <!--                        <ul class="sub-menu">
                                                    <li><a href="">Video Gallery</a></li>	
                                                </ul>-->
                    </li>
                    <li><a href="<?= BASE_URL; ?>new-releases/">New releases</a></li>
                    <li><a href="<?= BASE_URL; ?>custom-tracks/">Custom Tracks</a></li>
                    <li><a href="<?= BASE_URL; ?>success-stories/">Success stories</a></li>
                    <!--<li><a href="<?= BASE_URL; ?>pitch/">Pitch</a></li>-->
                    <li data-toggle="modal" data-target="#myModal"><a>Version</a></li>
                    <li><a href="<?= BASE_URL; ?>links/">Links</a></li>
<!--                    <li><a href="<?= BASE_URL; ?>contact/">Contact</a>
                    </li>-->
                </ul>
            </div>
            <!--<button class="btn btn-info" style="float: right;"><i class="fa fa-search"></i></button>-->

        </div>
    </div>
</div>