<style type="text/css">
    table.table td { vertical-align: middle; }
    table.table td input, select { margin: 0; }
</style>

<h2>Permisos de Usuario</h2>
<p><b>Usuario:</b> <?php echo $this->info['usuario']; ?><br><b>Role:</b><?php echo $this->info['role']; ?></p>
<form method="POST" action="" name="form1">
    <input type="hidden" name="guardar" value="1">
    <?php if (isset($this->permisos) && count($this->permisos)): ?>
        <table class="table table-bordered table-striped table-condensed" style="width: 500px;">        
            <tr>
                <td>Permiso</td>
                <td></td>
            </tr>
            <?php foreach ($this->permisos as $pr): ?>
                <?php
                if ($this->role[$pr]['valor'] == 1) {
                    $v = "habilitado";
                } else {
                    $v = "denegado";
                }
                ?>
                <tr>
                    <td><?php echo $this->usuario[$pr]['permiso']; ?></td>
                    <td>
                        <select name="perm_<?php echo $this->usuario[$pr]['id']; ?>">
                            <option value="x" <?php if ($this->usuario[$pr]['heredado']) echo "selected='selected'"; ?>>Heredado (<?php echo $v; ?>)</option>
                            <option value="1" <?php if ($this->usuario[$pr]['valor'] == 1 && $this->usuario[$pr]['heredado'] == "") echo "selected='selected'"; ?>>Habilitado</option>
                            <option value="" <?php if ($this->usuario[$pr]['valor'] == "" && $this->usuario[$pr]['heredado'] == "") echo "selected='selected'"; ?>>Denegado</option>
                        </select>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <p><button type="submit" value="guardar" class="btn btn-primary"><i class="icon-ok icon-white"> </i> Guardar</button></p>
    <?php endif; ?>
</form>