<div class="contenido-user-left left">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-body">
            <?php $this->panel->GetCustomOrders(); ?>
        </div>

    </div>
<!--    <div class="publicidad">
        <div class="publicidad-column columna-4" id="publicidad-panel-1">
            <div class="publicidad-item publicidad-active">
                
                                <div class="publicidad-item-default">
                                    <span>ID1.1</span>
                                </div>
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">advertise here</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="http://www.advertising.superbackings.com" target="_BLANCK">advertising.superbackings.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Do you want to increase the traffic to your website?
                </div>
            </div>
            <div class="publicidad-item publicidad-active">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">Singing out of tune?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    We offer the voice pitch service. Your vocals will be perfectly in tune.
                </div>
            </div>
            <div class="publicidad-item">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">custom tracks?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Custom backing tracks specially made for you.
                </div>
            </div>
           
        </div>
        <div class="publicidad-column columna-4" id="publicidad-panel-2">
            <div class="publicidad-item publicidad-active">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">custom tracks?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Custom backing tracks specially made for you.
                </div>
            </div>
             <div class="publicidad-item">
                
                                <div class="publicidad-item-default">
                                    <span>ID1.1</span>
                                </div>
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">advertise here</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="http://www.advertising.superbackings.com" target="_BLANCK">advertising.superbackings.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Do you want to increase the traffic to your website?
                </div>
            </div>
            <div class="publicidad-item">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">Singing out of tune?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    We offer the voice pitch service. Your vocals will be perfectly in tune.
                </div>
            </div>
        </div>
        <div class="publicidad-column columna-4" id="publicidad-panel-3">
            <div class="publicidad-item publicidad-active">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">Singing out of tune?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    We offer the voice pitch service. Your vocals will be perfectly in tune.
                </div>
            </div>
            <div class="publicidad-item">
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">custom tracks?</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="mailto:superbackingtracks@gmail.com" target="_BLANCK">superbackingtracks@gmail.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Custom backing tracks specially made for you.
                </div>
            </div>
             <div class="publicidad-item">
                
                                <div class="publicidad-item-default">
                                    <span>ID1.1</span>
                                </div>
                <div class="publicidad-title">
                    <span><a target="_BLANCK" href="http://www.advertising.superbackings.com">advertise here</a></span>
                </div>
                <div class="publicidad-url">
                    <a href="http://www.advertising.superbackings.com" target="_BLANCK">advertising.superbackings.com</a>
                </div>
                <div class="publicidad-descripcion">
                    Do you want to increase the traffic to your website?
                </div>
            </div>
        </div>
    </div>-->
</div>