<?php

?>
<div class="success-pagament">
    <?php HTML::br(); ?>
    <p align="center" class="designemail">
        <b>
            <a href="<?= BASE_URL . "usuarios/panel/" ?>" class="btn btn-info">ENTER TO YOUR YOUR CUSTOMER PANEL AND DOWNLOAD YOUR MUSIC</a>
        </b>
    </p>
    <p align="center" class="designemail">If you have requested pitched music , 
        Remember we are processing the pitch of the songs, it should not take more than 5 minutes per song. 
    </p>
    <p align="center" class="designemail">
        <b>
            Important: Your order will be active for 30 days, after this period you’ll need to buy again
        </b>
    </p>

    <p align="center" class="designemail">Thank you very much!</p>

    <p align="center">
        <span class="designemail">
            <b>
                superbackings.com 
            </b>
            <br>
            Making music since 1997
        </span>
        <br>
    </p>
</div>