<h2>Administración de permisos</h2>

<?php if (isset($this->permisos) && count($this->permisos)): ?>
    <table class="table table-bordered table-condensed table-striped" style="width:500px;">
        <tr>
            <th>ID</th>
            <th>Permiso</th>
            <th>Llave</th>
            <th></th>
        </tr>
        <?php foreach ($this->permisos as $rl): ?>    
            <tr>
                <td><?php echo $rl['id_permiso']; ?></td>
                <td><?php echo $rl['permiso']; ?></td>
                <td><?php echo $rl['keys']; ?></td>
                <td>Editar</td>
            </tr>

        <?php endforeach; ?>

    </table>
<?php endif; ?>

<p><a href="<?php echo $_layoutParams['root'];?>acl/nuevo_permiso" class="btn btn-primary"><i class="icon-plus-sign icon-white"> </i> Agregar Permiso</a></p>