<h2>Administración de roles</h2>
<?php if (isset($this->roles) && count($this->roles)): ?>
    <table class="table table-bordered table-condensed table-striped">
        <tr>
            <th>ID</th>
            <th>Role</th>
            <th>Permisos</th>
            <th>Editar</th>
        </tr>
        <?php foreach ($this->roles as $key): ?>
            <tr>
                <td><?php echo $key['id_role']; ?></td>
                <td><?php echo$key['role']; ?></td>
                <td><a href="<?php echo $_layoutParams['root']; ?>acl/permisos_role/<?php echo $key['id_role']; ?>">Permisos</a></td>
                <td>Editar</td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<p><a class="btn btn-primary" href="<?php echo $_layoutParams['root'];?>acl/nuevo_role"><i class="icon-plus-sign icon-white"> </i> Agregar Role</a></p>